In [1]:
import pandas as pd

In [4]:
data = pd.read_csv('Train.csv')
test = pd.read_csv('Test.csv')

In [3]:
data.shape

(8523, 12)

In [5]:
test.shape

(5681, 11)

In [4]:
data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [6]:
data['Item_Identifier'].value_counts()

FDW13    10
FDG33    10
NCY18     9
FDD38     9
DRE49     9
         ..
FDY43     1
FDQ60     1
FDO33     1
DRF48     1
FDC23     1
Name: Item_Identifier, Length: 1559, dtype: int64

In [12]:
data['Item_Type'].value_counts()

Fruits and Vegetables    1232
Snack Foods              1200
Household                 910
Frozen Foods              856
Dairy                     682
Canned                    649
Baking Goods              648
Health and Hygiene        520
Soft Drinks               445
Meat                      425
Breads                    251
Hard Drinks               214
Others                    169
Starchy Foods             148
Breakfast                 110
Seafood                    64
Name: Item_Type, dtype: int64

In [7]:
data[data['Item_Identifier']=='FDW13']

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
256,FDW13,8.5,Low Fat,0.098438,Canned,51.1324,OUT017,2007,NaN,Tier 2,Supermarket Type1,259.6620
1141,FDW13,8.5,Low Fat,0.097866,Canned,51.1324,OUT035,2004,Small,Tier 2,Supermarket Type1,1350.2424
2190,FDW13,8.5,Low Fat,0.098283,Canned,51.3324,OUT018,2009,Medium,Tier 3,Supermarket Type2,934.7832
3928,FDW13,NaN,Low Fat,0.097411,Canned,52.7324,OUT027,1985,Medium,Tier 3,Supermarket Type3,2492.7552
3978,FDW13,8.5,Low Fat,0.098037,Canned,51.5324,OUT049,1999,Medium,Tier 1,Supermarket Type1,882.8508
6499,FDW13,8.5,Low Fat,0.098083,Canned,50.3324,OUT045,2002,NaN,Tier 2,Supermarket Type1,675.1212
6587,FDW13,8.5,low fat,0.163839,Canned,51.3324,OUT010,1998,NaN,Tier 3,Grocery Store,311.5944
7029,FDW13,8.5,Low Fat,0.097803,Canned,50.5324,OUT013,1987,High,Tier 3,Supermarket Type1,882.8508
8025,FDW13,NaN,Low Fat,0.171384,Canned,50.5324,OUT019,1985,Small,Tier 1,Grocery Store,207.7296
8032,FDW13,8.5,Low Fat,0.097885,Canned,52.5324,OUT046,1997,Small,Tier 1,Supermarket Type1,1194.4452

In [8]:
data[data['Item_Identifier']=='FDG33']

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
231,FDG33,NaN,Regular,0.139561,Seafood,170.4764,OUT027,1985,Medium,Tier 3,Supermarket Type3,3435.5280
1202,FDG33,5.365,Regular,0.140525,Seafood,172.7764,OUT045,2002,NaN,Tier 2,Supermarket Type1,2233.0932
1575,FDG33,NaN,Regular,0.245543,Seafood,172.2764,OUT019,1985,Small,Tier 1,Grocery Store,171.7764
2728,FDG33,5.365,Regular,0.234733,Seafood,173.4764,OUT010,1998,NaN,Tier 3,Grocery Store,171.7764
4747,FDG33,5.365,Regular,0.140458,Seafood,169.7764,OUT049,1999,Medium,Tier 1,Supermarket Type1,3263.7516
5164,FDG33,5.365,Regular,0.140240,Seafood,171.0764,OUT046,1997,Small,Tier 1,Supermarket Type1,3263.7516
6112,FDG33,5.365,Regular,0.141034,Seafood,173.6764,OUT017,2007,NaN,Tier 2,Supermarket Type1,858.8820
7011,FDG33,5.365,Regular,0.140812,Seafood,173.5764,OUT018,2009,Medium,Tier 3,Supermarket Type2,2061.3168
7098,FDG33,5.365,Regular,0.140124,Seafood,172.0764,OUT013,1987,High,Tier 3,Supermarket Type1,2748.4224
7726,FDG33,5.365,Regular,0.140214,Seafood,173.7764,OUT035,2004,Small,Tier 2,Supermarket Type1,4637.9628

In [9]:
data[data['Item_Identifier']=='NCY18']

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
342,NCY18,7.285,Low Fat,0.031126,Household,174.3054,OUT013,1987,High,Tier 3,Supermarket Type1,4377.6350
736,NCY18,7.285,Low Fat,0.031146,Household,173.6054,OUT035,2004,Small,Tier 2,Supermarket Type1,2626.5810
1639,NCY18,7.285,Low Fat,0.031215,Household,177.1054,OUT045,2002,NaN,Tier 2,Supermarket Type1,2626.5810
1756,NCY18,7.285,Low Fat,0.031328,Household,174.6054,OUT017,2007,NaN,Tier 2,Supermarket Type1,2976.7918
2079,NCY18,7.285,Low Fat,0.052141,Household,174.9054,OUT010,1998,NaN,Tier 3,Grocery Store,525.3162
2976,NCY18,7.285,Low Fat,0.031152,Household,173.2054,OUT046,1997,Small,Tier 1,Supermarket Type1,4902.9512
4233,NCY18,NaN,Low Fat,0.031001,Household,177.0054,OUT027,1985,Medium,Tier 3,Supermarket Type3,2101.2648
6050,NCY18,7.285,Low Fat,0.031200,Household,174.7054,OUT049,1999,Medium,Tier 1,Supermarket Type1,6303.7944
7869,NCY18,7.285,Low Fat,0.031279,Household,176.0054,OUT018,2009,Medium,Tier 3,Supermarket Type2,2626.5810

* We can understand one pattern here is like Item_Identifier and Item_Type shares the same thing, in the Item_Identifier we have lot of ctegorical values so instead of using Item_Identifier we can use Item_Type for further works.

In [10]:
data['Outlet_Identifier'].value_counts()

OUT027    935
OUT013    932
OUT049    930
OUT046    930
OUT035    930
OUT045    929
OUT018    928
OUT017    926
OUT010    555
OUT019    528
Name: Outlet_Identifier, dtype: int64

In [11]:
data['Outlet_Type'].value_counts()

Supermarket Type1    5577
Grocery Store        1083
Supermarket Type3     935
Supermarket Type2     928
Name: Outlet_Type, dtype: int64

In [14]:
data[data['Outlet_Identifier'] == 'OUT027'].sample(21).T

,2053,5084,991,1998,793,7562,4814,6763,6994,449,...,892,5546,2402,1092,6537,3770,557,6000,1009,4803
Item_Identifier,FDG44,FDP56,FDS44,FDZ43,NCJ29,FDY39,FDE57,FDZ49,FDK22,NCO54,...,NCO17,FDX01,FDA02,NCB43,FDR52,NCC18,FDZ22,FDO37,FDU14,NCW42
Item_Weight,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Item_Fat_Content,Low Fat,Low Fat,Regular,Regular,Low Fat,Regular,Low Fat,Regular,Low Fat,Low Fat,...,Low Fat,Low Fat,Regular,Low Fat,Regular,Low Fat,Low Fat,Low Fat,Low Fat,Low Fat
Item_Visibility,0.0,0.046259,0.155288,0.056782,0.035023,0.0,0.036109,0.132501,0.02596,0.014205,...,0.073024,0.024047,0.029579,0.099428,0.075676,0.176412,0.045051,0.021273,0.034584,0.058186
Item_Type,Fruits and Vegetables,Fruits and Vegetables,Fruits and Vegetables,Fruits and Vegetables,Health and Hygiene,Meat,Fruits and Vegetables,Canned,Snack Foods,Household,...,Health and Hygiene,Canned,Dairy,Household,Frozen Foods,Household,Snack Foods,Breakfast,Dairy,Household
Item_MRP,55.7298,47.4692,241.7538,241.2512,85.1224,182.0608,140.6154,220.3798,214.885,56.7614,...,121.844,115.515,143.5786,187.8898,190.4846,173.2422,84.925,229.1326,248.375,220.8456
Outlet_Identifier,OUT027,OUT027,OUT027,OUT027,OUT027,OUT027,OUT027,OUT027,OUT027,OUT027,...,OUT027,OUT027,OUT027,OUT027,OUT027,OUT027,OUT027,OUT027,OUT027,OUT027
Outlet_Establishment_Year,1985,1985,1985,1985,1985,1985,1985,1985,1985,1985,...,1985,1985,1985,1985,1985,1985,1985,1985,1985,1985
Outlet_Size,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium,...,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium
Outlet_Location_Type,Tier 3,Tier 3,Tier 3,Tier 3,Tier 3,Tier 3,Tier 3,Tier 3,Tier 3,Tier 3,...,Tier 3,Tier 3,Tier 3,Tier 3,Tier 3,Tier 3,Tier 3,Tier 3,Tier 3,Tier 3
Outlet_Type,Supermarket Type3,Supermarket Type3,Supermarket Type3,Supermarket Type3,Supermarket Type3,Supermarket Type3,Supermarket Type3,Supermarket Type3,Supermarket Type3,Supermarket Type3,...,Supermarket Type3,Supermarket Type3,Supermarket Type3,Supermarket Type3,Supermarket Type3,Supermarket Type3,Supermarket Type3,Supermarket Type3,Supermarket Type3,Supermarket Type3
Item_Outlet_Sales,2804.3496,1576.6144,9133.4444,8239.9408,2045.3376,7717.9536,4538.0928,5289.1152,4976.855,2486.763,...,3115.944,1980.755,3756.4436,7296.5022,8789.8916,2069.3064,1747.725,7393.0432,10236.675,4199.8664

In [15]:
data[data['Outlet_Identifier'] == 'OUT013'].sample(21).T

,2228,1511,3708,3454,4632,4680,8195,1928,2278,2676,...,4448,818,3161,2026,4765,1806,3331,1145,6922,4783
Item_Identifier,FDQ19,NCC31,FDC44,FDD14,FDS20,FDQ48,DRA24,FDZ10,FDC08,DRN47,...,FDX03,NCP50,DRB25,FDR32,FDN09,FDN25,FDH40,FDD09,DRN35,NCX05
Item_Weight,7.35,8.02,15.6,20.7,8.85,14.3,19.35,17.85,19.0,12.1,...,15.85,17.35,12.3,6.78,14.15,7.895,11.6,13.5,8.01,15.2
Item_Fat_Content,Regular,Low Fat,Low Fat,Low Fat,Low Fat,reg,Regular,Low Fat,Regular,Low Fat,...,Regular,Low Fat,Low Fat,Regular,Low Fat,Regular,Regular,Low Fat,Low Fat,Low Fat
Item_Visibility,0.014353,0.0,0.172453,0.169667,0.053822,0.034383,0.039895,0.044426,0.103364,0.016813,...,0.061045,0.020543,0.069402,0.085737,0.034846,0.061125,0.078864,0.0,0.070189,0.096981
Item_Type,Fruits and Vegetables,Household,Fruits and Vegetables,Canned,Fruits and Vegetables,Baking Goods,Soft Drinks,Snack Foods,Fruits and Vegetables,Hard Drinks,...,Meat,Others,Soft Drinks,Fruits and Vegetables,Snack Foods,Breakfast,Frozen Foods,Fruits and Vegetables,Hard Drinks,Health and Hygiene
Item_MRP,242.6512,157.7972,115.1518,183.5266,183.8292,96.5726,162.4868,124.902,226.172,180.666,...,44.7744,80.5618,107.9938,229.5694,242.7828,58.5588,83.2276,179.9976,37.9532,116.3492
Outlet_Identifier,OUT013,OUT013,OUT013,OUT013,OUT013,OUT013,OUT013,OUT013,OUT013,OUT013,...,OUT013,OUT013,OUT013,OUT013,OUT013,OUT013,OUT013,OUT013,OUT013,OUT013
Outlet_Establishment_Year,1987,1987,1987,1987,1987,1987,1987,1987,1987,1987,...,1987,1987,1987,1987,1987,1987,1987,1987,1987,1987
Outlet_Size,High,High,High,High,High,High,High,High,High,High,...,High,High,High,High,High,High,High,High,High,High
Outlet_Location_Type,Tier 3,Tier 3,Tier 3,Tier 3,Tier 3,Tier 3,Tier 3,Tier 3,Tier 3,Tier 3,...,Tier 3,Tier 3,Tier 3,Tier 3,Tier 3,Tier 3,Tier 3,Tier 3,Tier 3,Tier 3
Outlet_Type,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,...,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1
Item_Outlet_Sales,969.4048,1713.7692,683.1108,4426.2384,2554.0088,2251.0698,4422.2436,1897.53,3169.208,4134.618,...,181.0976,322.2472,2036.6822,3425.541,3167.8764,171.7764,1543.3244,4889.6352,826.9236,2548.6824

In [16]:
data[data['Outlet_Identifier'] == 'OUT046'].sample(21).T

,6113,2591,8331,1522,4998,4412,5369,58,1871,8136,...,1408,2689,3872,2077,8309,5419,4289,5246,2737,8017
Item_Identifier,FDE38,DRD12,FDB57,FDQ56,FDF56,FDB49,FDN40,FDY21,FDJ28,FDR37,...,FDD40,NCX06,FDW44,FDF22,FDW39,NCD54,NCM05,NCH30,FDA33,FDL43
Item_Weight,6.52,6.96,20.25,6.59,16.7,8.3,5.88,15.1,12.3,16.5,...,20.25,17.6,9.5,6.865,6.69,21.1,6.825,17.1,6.48,10.1
Item_Fat_Content,Low Fat,Low Fat,Regular,Low Fat,Regular,Regular,Low Fat,Low Fat,Low Fat,Regular,...,Regular,Low Fat,Regular,Low Fat,Regular,Low Fat,Low Fat,Low Fat,Low Fat,Low Fat
Item_Visibility,0.044607,0.077194,0.018805,0.105597,0.119462,0.030151,0.0,0.173481,0.021861,0.06625,...,0.014793,0.015687,0.035151,0.056831,0.03691,0.029009,0.059847,0.067154,0.0339,0.027064
Item_Type,Canned,Soft Drinks,Fruits and Vegetables,Fruits and Vegetables,Fruits and Vegetables,Baking Goods,Frozen Foods,Snack Foods,Frozen Foods,Breakfast,...,Dairy,Household,Fruits and Vegetables,Snack Foods,Meat,Household,Health and Hygiene,Household,Snack Foods,Meat
Item_MRP,164.2842,89.9146,220.6772,83.4908,182.7976,98.7384,154.2998,194.511,193.3162,183.3292,...,191.5162,182.6976,171.8448,214.0218,175.037,143.3786,262.5226,114.386,146.9076,76.367
Outlet_Identifier,OUT046,OUT046,OUT046,OUT046,OUT046,OUT046,OUT046,OUT046,OUT046,OUT046,...,OUT046,OUT046,OUT046,OUT046,OUT046,OUT046,OUT046,OUT046,OUT046,OUT046
Outlet_Establishment_Year,1997,1997,1997,1997,1997,1997,1997,1997,1997,1997,...,1997,1997,1997,1997,1997,1997,1997,1997,1997,1997
Outlet_Size,Small,Small,Small,Small,Small,Small,Small,Small,Small,Small,...,Small,Small,Small,Small,Small,Small,Small,Small,Small,Small
Outlet_Location_Type,Tier 1,Tier 1,Tier 1,Tier 1,Tier 1,Tier 1,Tier 1,Tier 1,Tier 1,Tier 1,...,Tier 1,Tier 1,Tier 1,Tier 1,Tier 1,Tier 1,Tier 1,Tier 1,Tier 1,Tier 1
Outlet_Type,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,...,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1
Item_Outlet_Sales,2818.3314,1277.0044,2223.772,1342.2528,1810.976,492.692,1999.3974,4910.275,3078.6592,2006.7212,...,3078.6592,3440.8544,2556.672,5556.7668,2117.244,866.8716,9779.9362,1245.046,2956.152,765.67

In [17]:
data[data['Outlet_Identifier'] == 'OUT017'].sample(21).T

,1475,2272,7125,3394,1760,2999,3504,1936,7956,2342,...,4301,4526,1676,7864,2907,223,2644,3874,5717,367
Item_Identifier,FDP52,DRC01,FDW09,FDV16,DRE15,FDI26,FDK09,FDD59,FDQ24,FDC21,...,FDJ56,DRO35,FDP39,FDV57,NCD19,FDT25,FDO04,FDZ58,NCX17,FDS15
Item_Weight,18.7,5.92,13.65,7.75,13.35,5.94,15.2,10.5,15.7,14.6,...,8.985,13.85,12.65,15.25,8.93,7.5,16.6,17.85,21.25,9.195
Item_Fat_Content,Regular,Regular,Regular,Regular,Low Fat,Low Fat,Low Fat,Regular,Low Fat,Regular,...,Low Fat,LF,Low Fat,Regular,Low Fat,Low Fat,Low Fat,Low Fat,Low Fat,Regular
Item_Visibility,0.071092,0.019309,0.026067,0.0834,0.0,0.035084,0.092282,0.066555,0.074083,0.043202,...,0.18444,0.034766,0.069818,0.066269,0.013254,0.051038,0.0,0.052472,0.114246,0.078502
Item_Type,Frozen Foods,Soft Drinks,Snack Foods,Frozen Foods,Dairy,Canned,Snack Foods,Starchy Foods,Baking Goods,Fruits and Vegetables,...,Fruits and Vegetables,Hard Drinks,Meat,Snack Foods,Household,Canned,Frozen Foods,Snack Foods,Health and Hygiene,Meat
Item_MRP,228.601,49.0692,78.8302,34.5558,75.7012,176.4344,227.2352,80.896,253.3724,110.1254,...,99.67,114.2492,53.5324,179.666,56.4614,121.7072,54.6614,123.7072,231.23,108.7596
Outlet_Identifier,OUT017,OUT017,OUT017,OUT017,OUT017,OUT017,OUT017,OUT017,OUT017,OUT017,...,OUT017,OUT017,OUT017,OUT017,OUT017,OUT017,OUT017,OUT017,OUT017,OUT017
Outlet_Establishment_Year,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,...,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007
Outlet_Size,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Outlet_Location_Type,Tier 2,Tier 2,Tier 2,Tier 2,Tier 2,Tier 2,Tier 2,Tier 2,Tier 2,Tier 2,...,Tier 2,Tier 2,Tier 2,Tier 2,Tier 2,Tier 2,Tier 2,Tier 2,Tier 2,Tier 2
Outlet_Type,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,...,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1
Item_Outlet_Sales,4823.721,1478.076,713.0718,441.4254,1442.1228,2141.2128,4122.6336,958.752,6795.1548,1844.9318,...,3295.71,1853.5872,830.9184,6471.576,828.921,3552.7088,884.1824,2450.144,3029.39,2588.6304

* There is also a pattern here like Outlet_Identifier and Outlet_Type shares the same thing, in the Outlet_Identifier we have lot of categorical values so instead of using Outlet_Identifier we can use Outlet_Type for further works.
* Other Pattern is Outlet_Identifier Indentifies the Outlet_Location_Type of same Outlet_Type.

In [18]:
data.drop(columns=['Item_Identifier', 'Outlet_Identifier'], inplace=True)

In [19]:
data['Outlet_Establishment_Year'].value_counts()

1985    1463
1987     932
1999     930
1997     930
2004     930
2002     929
2009     928
2007     926
1998     555
Name: Outlet_Establishment_Year, dtype: int64

In [35]:
data[data['Outlet_Establishment_Year']==1998][['Outlet_Type', 'Outlet_Location_Type']].value_counts()

Outlet_Type    Outlet_Location_Type
Grocery Store  Tier 3                  555
dtype: int64

In [38]:
data[data['Outlet_Establishment_Year']==1998][['Item_Type','Outlet_Type', 'Outlet_Location_Type']].value_counts()

Item_Type              Outlet_Type    Outlet_Location_Type
Fruits and Vegetables  Grocery Store  Tier 3                  79
Snack Foods            Grocery Store  Tier 3                  71
Household              Grocery Store  Tier 3                  67
Frozen Foods           Grocery Store  Tier 3                  54
Dairy                  Grocery Store  Tier 3                  43
Baking Goods           Grocery Store  Tier 3                  42
Health and Hygiene     Grocery Store  Tier 3                  37
Canned                 Grocery Store  Tier 3                  35
Meat                   Grocery Store  Tier 3                  34
Soft Drinks            Grocery Store  Tier 3                  28
Breads                 Grocery Store  Tier 3                  17
Hard Drinks            Grocery Store  Tier 3                  16
Others                 Grocery Store  Tier 3                  10
Breakfast              Grocery Store  Tier 3                   9
Starchy Foods          Grocery Store  Tier 3                   9
Seafood                Grocery Store  Tier 3                   4
dtype: int64

In [47]:
for i in data['Outlet_Establishment_Year'].unique():
    print(f'Year {i}')
    print(data[data['Outlet_Establishment_Year']==i][['Outlet_Size','Outlet_Type', 'Outlet_Location_Type']].value_counts())
    print('----------------------------------------------------------------------------------')

Year 1999
Outlet_Size  Outlet_Type        Outlet_Location_Type
Medium       Supermarket Type1  Tier 1                  930
dtype: int64
----------------------------------------------------------------------------------
Year 2009
Outlet_Size  Outlet_Type        Outlet_Location_Type
Medium       Supermarket Type2  Tier 3                  928
dtype: int64
----------------------------------------------------------------------------------
Year 1998
Series([], dtype: int64)
----------------------------------------------------------------------------------
Year 1987
Outlet_Size  Outlet_Type        Outlet_Location_Type
High         Supermarket Type1  Tier 3                  932
dtype: int64
----------------------------------------------------------------------------------
Year 1985
Outlet_Size  Outlet_Type        Outlet_Location_Type
Medium       Supermarket Type3  Tier 3                  935
Small        Grocery Store      Tier 1                  528
dtype: int64
----------------------------------------------------------------------------------
Year 2002
Series([], dtype: int64)
----------------------------------------------------------------------------------
Year 2007
Series([], dtype: int64)
----------------------------------------------------------------------------------
Year 1997
Outlet_Size  Outlet_Type        Outlet_Location_Type
Small        Supermarket Type1  Tier 1                  930
dtype: int64
----------------------------------------------------------------------------------
Year 2004
Outlet_Size  Outlet_Type        Outlet_Location_Type
Small        Supermarket Type1  Tier 2                  930
dtype: int64
----------------------------------------------------------------------------------

In [48]:
data[data['Outlet_Establishment_Year']==2007][['Outlet_Size','Outlet_Type', 'Outlet_Location_Type']]

     Outlet_Size        Outlet_Type Outlet_Location_Type
9            NaN  Supermarket Type1               Tier 2
25           NaN  Supermarket Type1               Tier 2
53           NaN  Supermarket Type1               Tier 2
54           NaN  Supermarket Type1               Tier 2
73           NaN  Supermarket Type1               Tier 2
...          ...                ...                  ...
8493         NaN  Supermarket Type1               Tier 2
8494         NaN  Supermarket Type1               Tier 2
8496         NaN  Supermarket Type1               Tier 2
8500         NaN  Supermarket Type1               Tier 2
8501         NaN  Supermarket Type1               Tier 2

[926 rows x 3 columns]

* The Sales data of year 1999 is from Supermarket Type1 which is located in Tier 1 Cities and have Medium size. And this pattern is applicable for all the years, this is not very convinent as such.
* Instead of this we can convert Establishment year into the age of Outlet, so we can derive the sales information in more convinent way, such as we can ask a question like: if any outlet is 20 years old situated in tier 3 city and has medium in size so how much sales has been genrated from there.

In [49]:
# substract current year from establishment year.
data['Age_Outlet'] = 2022 - data['Outlet_Establishment_Year']

In [50]:
# drop the Establishment year
data.drop(columns=['Outlet_Establishment_Year'], inplace=True)

In [56]:
data[data['Age_Outlet']==13]['Item_Outlet_Sales'].sum()

1851822.83

In [63]:
data.sample(10).T

,8264,1863,8002,2784,7321,3135,5715,7904,1207,3339
Item_Weight,13.6,19.35,17.25,11.5,19.35,8.42,6.89,12.5,13.8,15.0
Item_Fat_Content,Low Fat,Regular,Low Fat,LF,Regular,Regular,Regular,Low Fat,Low Fat,Low Fat
Item_Visibility,0.009991,0.021453,0.113518,0.173483,0.062626,0.0,0.136315,0.02074,0.097044,0.049039
Item_Type,Household,Fruits and Vegetables,Household,Fruits and Vegetables,Baking Goods,Canned,Snack Foods,Breads,Dairy,Soft Drinks
Item_MRP,175.537,120.3098,253.5724,129.0652,165.3184,229.0352,195.082,198.9742,57.493,65.4168
Outlet_Size,Small,Small,Small,Small,Medium,Small,High,NaN,Small,High
Outlet_Location_Type,Tier 2,Tier 2,Tier 1,Tier 2,Tier 1,Tier 2,Tier 3,Tier 2,Tier 2,Tier 3
Outlet_Type,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1,Supermarket Type1
Item_Outlet_Sales,3705.177,2530.7058,5033.448,3487.4604,1651.184,5496.8448,2703.148,995.371,1358.232,1661.8368
Age_Outlet,18,18,25,18,23,18,35,20,18,35